name: MacOS Workflow

on: [push]

jobs:
  clone:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }} # Check out the code of the PR head
      - name: Update submodules
        run: git submodule update --init --recursive

  Build:
    needs: clone
    runs-on: macos-latest
    steps:
      - name: List the directory
        run: ls -la ./
      - name: Run the build script
        run: . ./build_osx.sh
        working-directory: ./
