name: MacOS/Linux Build

on: [push]

jobs:
  macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Run the build script
        run: ./build.sh

  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Run the build script        
        run: ./build.sh
